name: analog_clock
description: Analog clock.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.15.0
  align_positioned: ^1.2.5
  video_player: ^0.10.3+3
  google_fonts: ^0.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/
    - assets/video/video_sunny.mp4
    - assets/video/video_rainy.mp4
    - assets/video/video_cloudy.mp4
    - assets/video/video_snowy.mp4
    - assets/fonts/MyFlutterApp.ttf
